# Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/axophy_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Impede o Hibernate de alterar as tabelas que já criamos via script SQL
spring.jpa.hibernate.ddl-auto=none

# Mostra as instruções SQL no terminal para depuração
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Porta da nossa API REST
server.port=8080